basePath: /
definitions:
  handler.CreateTodoRequest:
    properties:
      text:
        example: some text
        type: string
    type: object
  handler.CreateTodoResponse:
    type: object
  handler.ErrorResponse:
    properties:
      error:
        example: something went wrong
        type: string
    type: object
  handler.GetTodoResponse:
    properties:
      id:
        example: 4b6158b9-bc03-4058-93b8-a0a1fcab7371
        type: string
      text:
        example: some text
        type: string
    type: object
  handler.UpdateTodoRequest:
    properties:
      text:
        example: some text
        type: string
    type: object
  handler.UpdateTodoResponse:
    type: object
host: localhost:4141
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Todo API
  title: Todo
  version: "1.0"
paths:
  /todos:
    post:
      consumes:
      - application/json
      description: Create todo
      parameters:
      - description: Text
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/handler.CreateTodoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateTodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create todo
      tags:
      - todos
  /todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateTodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete todo
      tags:
      - todos
    get:
      consumes:
      - application/json
      description: Get todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetTodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get todo
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Update todo
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      - description: Text
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateTodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateTodoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Update todo
      tags:
      - todos
swagger: "2.0"
