apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo
  labels:
    name: todo
spec:
  selector: 
    matchLabels:
      name: todo
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  todo
    spec:
      containers:
      - image: softwareaccessdockerid/todo-service:1.0.0
        imagePullPolicy: Always
        name:  todo
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100"
        env:
        - name: WEB_PORT
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: todo_port
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}


---

kind: Service
apiVersion: v1
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: ClusterIP
  ports:
  - name:  web-port
    port:  80
    targetPort:  4141