apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo
  labels:
    name: todo
spec:
  selector: 
    matchLabels:
      app: todo
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  todo
    spec:
      containers:
      - image: todo-service:0.0.1
        imagePullPolicy: IfNotPresent 
        name:  todo
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        ports:
        - containerPort:  4141
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.ini
      volumes:
        - name: config-volume
          configMap:
            name: todo-config-v1

---

apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: NodePort 
  ports:
  - name:  web-port
    port:  4141
  - name: grpc-port
    port: 50001