apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user
  labels:
    name: user
spec:
  selector: 
    matchLabels:
      name: user
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - image: softwareaccessdockerid/todo-service:1.0.0
        imagePullPolicy: Always
        name:  user
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100"

---

kind: Service
apiVersion: v1
metadata:
  name: user
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
  - name:  web-port
    port:  80
    targetPort:  4242