apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user
  labels:
    name: user
spec:
  selector: 
    matchLabels:
      app: user
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: user-service:0.0.1
        imagePullPolicy: IfNotPresent
        name:  user
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.ini
      volumes:
        - name: config-volume
          configMap:
            name: todo-config-v1

---

kind: Service
apiVersion: v1
metadata:
  name: user
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
  - name:  web-port
    port:  80
    targetPort:  4242
