# Create a persistent volume claim for the Postgres deployment
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv

---

# Create a persistent volume for the Postgres deployment
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  claimRef:
    namespace: default
    name: postgres-pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /var/lib/postgresql/data
  
